
###
POST http://localhost:8080/api/employee/logout
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

###
GET http://127.0.0.1:8080/backend/index.html

###
GET http://localhost:8080/backend/page/login/login.html

###
GET  http://localhost:8080/employee/page?page=1&pageSize=10

###
POST  http://localhost:8080/user/sendMsg
Content-Type: application/json

{
  "phone": "13289381428"
}

###
POST http://localhost:8080/user/login
Content-Type:  application/json

{
  "phone": "13289381428",
  "code": "8719"
}