name: Java CI with Maven

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify && mkdir staging
    - name: Upload jar
      run: mkdir tmpdir && cp target/*.jar tmpdir
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: tmpdir
